version: '3'

services:
  db:
    image: postgres:alpine
    restart: on-failure:5
    env_file:
      - ./.env
    volumes:
      - urlshortener_db:/tmp/pgdata
    ports:
      - "5432:5432"
  redis:
    image: redis:5.0.7
    ports:
      - "6379:6379"
    restart: always

volumes:
    urlshortener_db: