# Generated by Django 4.1 on 2022-08-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Url",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("long_url", models.CharField(max_length=512)),
                ("key", models.CharField(max_length=7, unique=True)),
                ("user_id", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "url",
                "verbose_name_plural": "urls",
            },
        ),
        migrations.AddIndex(
            model_name="url",
            index=models.Index(fields=["long_url"], name="urls_url_long_ur_bf7313_idx"),
        ),
        migrations.AddIndex(
            model_name="url",
            index=models.Index(fields=["key"], name="urls_url_key_59c420_idx"),
        ),
        migrations.AddIndex(
            model_name="url",
            index=models.Index(fields=["user_id"], name="urls_url_user_id_e08e89_idx"),
        ),
    ]
