# Generated by Django 4.1 on 2022-08-28 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("urls", "0002_alter_url_long_url"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="url",
            name="urls_url_key_59c420_idx",
        ),
        migrations.RemoveIndex(
            model_name="url",
            name="urls_url_user_id_e08e89_idx",
        ),
        migrations.RenameField(
            model_name="url",
            old_name="user_id",
            new_name="hit",
        ),
    ]
