# Generated by Django 4.1 on 2022-08-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("keys", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="key",
            name="is_used",
            field=models.BooleanField(default=False),
        ),
        migrations.RunSQL("ALTER SEQUENCE keys_key_id_seq RESTART WITH 100000000"),
    ]
